version: 2
jobs:
  build:
    docker:
      - image: circleci/node:7.10
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: npm test
      - run: npm run dist
      - deploy:
          command: if [ "${CIRCLE_BRANCH}" == "master" ]; then ssh -oStrictHostKeyChecking=no circleci@sleepy.fish hostname && ssh -oStrictHostKeyChecking=no circleci@sleepy.fish touch /var/www/sleepy.fish/foo && scp -oStrictHostKeyChecking=no -r dist/* circleci@sleepy.fish:/var/www/sleepy.fish; fi