version: 2
jobs:
  build:
    docker:
      - image: circleci/node:7.10
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: npm run dist
  test:
    docker:
      - image: circleci/node:7.10
    steps:
      - checkout
      - run: npm test
  deploy:
    docker:
      - image: circleci/node:7.10
    branches:
      only:
        - master
    steps:
      - deploy:
          command: if [ "${CIRCLE_BRANCH}" == "master" ]; then scp -oStrictHostKeyChecking=no -r dist/* circleci@sleepy.fish:/var/www/sleepy.fish; fi
workflows:
  version: 2
  launch:
    jobs:
      - build
      - test
      - deploy


    
